title: GitHub pages with jekyll...
author: lee court nine eight
email: hello at ... dot com
description: > # this means to ignore newlines until "baseurl:"
 insert into index.

# social links
twitter_username: not-applicable
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
